# Generated by Django 5.1.7 on 2025-04-06 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
        migrations.AddField(
            model_name='course',
            name='pdfs',
            field=models.FileField(blank=True, null=True, upload_to='courses/pdfs/', verbose_name='PDF Document'),
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], default='video', max_length=50),
        ),
        migrations.CreateModel(
            name='CoursePdfInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512)),
                ('table_of_contents', models.JSONField(blank=True, default=list)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_internal_data', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('pdf_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.coursepdfinternal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
